from typing import Protocol, runtime_checkable

@runtime_checkable
class UnitOfWork(Protocol):
    # Example: users: UsersRepo
    # Replace or extend with service-specific repositories.

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...